# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 21:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Margarete', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtTeilnahme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=60)),
                ('erstelldatum', models.DateTimeField(auto_now_add=True)),
                ('beschreibung', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fachbereich',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=60)),
                ('erstelldatum', models.DateTimeField(auto_now_add=True)),
                ('beschreibung', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KonkreteWettbewerbsrunde',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=60)),
                ('erstelldatum', models.DateTimeField(auto_now_add=True)),
                ('beschreibung', models.CharField(blank=True, max_length=500, null=True)),
                ('nummer', models.IntegerField(blank=True, null=True)),
                ('jahr', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=60)),
                ('erstelldatum', models.DateTimeField(auto_now_add=True)),
                ('beschreibung', models.CharField(blank=True, max_length=500, null=True)),
                ('vorname', models.CharField(max_length=60)),
                ('nachname', models.CharField(max_length=60)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=60)),
                ('erstelldatum', models.DateTimeField(auto_now_add=True)),
                ('beschreibung', models.CharField(blank=True, max_length=500, null=True)),
                ('fachbereich', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Margarete.Fachbereich')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teilnahme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Margarete.Person')),
                ('teilnahmeart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Margarete.ArtTeilnahme')),
            ],
        ),
        migrations.CreateModel(
            name='Teilnahmekonzept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=60)),
                ('erstelldatum', models.DateTimeField(auto_now_add=True)),
                ('beschreibung', models.CharField(blank=True, max_length=500, null=True)),
                ('teilnahmearten', models.ManyToManyField(to='Margarete.ArtTeilnahme')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Veranstaltung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=60)),
                ('erstelldatum', models.DateTimeField(auto_now_add=True)),
                ('beschreibung', models.CharField(blank=True, max_length=500, null=True)),
                ('ort', models.CharField(blank=True, max_length=20, null=True)),
                ('zeitBeginn', models.DateField(blank=True, null=True, verbose_name='Zeitpunkt vom Beginn der Veranstaltung')),
                ('zeitEnde', models.DateField(blank=True, null=True, verbose_name='Zeitpunkt vom Ende der Veranstaltung')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Wettbewerb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=60)),
                ('erstelldatum', models.DateTimeField(auto_now_add=True)),
                ('beschreibung', models.CharField(blank=True, max_length=500, null=True)),
                ('fachbereich', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Margarete.Fachbereich')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Wettbewerbsrunde',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=60)),
                ('erstelldatum', models.DateTimeField(auto_now_add=True)),
                ('beschreibung', models.CharField(blank=True, max_length=500, null=True)),
                ('runde', models.IntegerField()),
                ('teilnahmearten', models.ManyToManyField(to='Margarete.Teilnahmekonzept')),
                ('wettbewerb', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Margarete.Wettbewerb')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='ggg',
        ),
        migrations.CreateModel(
            name='KonkretesSeminar',
            fields=[
                ('veranstaltung_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Margarete.Veranstaltung')),
                ('seminar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Margarete.Seminar')),
            ],
            options={
                'abstract': False,
            },
            bases=('Margarete.veranstaltung',),
        ),
        migrations.CreateModel(
            name='sonstigeVeranstaltung',
            fields=[
                ('veranstaltung_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Margarete.Veranstaltung')),
            ],
            options={
                'abstract': False,
            },
            bases=('Margarete.veranstaltung',),
        ),
        migrations.CreateModel(
            name='Wettbewerbsveranstaltung',
            fields=[
                ('veranstaltung_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Margarete.Veranstaltung')),
            ],
            options={
                'abstract': False,
            },
            bases=('Margarete.veranstaltung',),
        ),
        migrations.AddField(
            model_name='veranstaltung',
            name='fachbereich',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Margarete.Fachbereich'),
        ),
        migrations.AddField(
            model_name='veranstaltung',
            name='teilnehmer',
            field=models.ManyToManyField(through='Margarete.Teilnahme', to='Margarete.Person'),
        ),
        migrations.AddField(
            model_name='teilnahme',
            name='veranstaltung',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Margarete.Veranstaltung'),
        ),
        migrations.AddField(
            model_name='konkretewettbewerbsrunde',
            name='wettbewerbsrunde',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Margarete.Wettbewerbsrunde'),
        ),
        migrations.AddField(
            model_name='wettbewerbsveranstaltung',
            name='konkreteWettbewerbsrunde',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Margarete.KonkreteWettbewerbsrunde'),
        ),
    ]
