# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 16:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Margarete', '0003_auto_20160818_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artteilnahme',
            name='urlbezeichnung',
        ),
        migrations.RemoveField(
            model_name='fachbereich',
            name='urlbezeichnung',
        ),
        migrations.RemoveField(
            model_name='konkretewettbewerbsrunde',
            name='urlbezeichnung',
        ),
        migrations.RemoveField(
            model_name='person',
            name='urlbezeichnung',
        ),
        migrations.RemoveField(
            model_name='seminar',
            name='urlbezeichnung',
        ),
        migrations.RemoveField(
            model_name='teilnahmekonzept',
            name='urlbezeichnung',
        ),
        migrations.RemoveField(
            model_name='veranstaltung',
            name='urlbezeichnung',
        ),
        migrations.RemoveField(
            model_name='wettbewerb',
            name='urlbezeichnung',
        ),
        migrations.RemoveField(
            model_name='wettbewerbsrunde',
            name='urlbezeichnung',
        ),
    ]
