# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Margarete', '0004_auto_20160818_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='artteilnahme',
            name='urlbezeichnung',
            field=models.SlugField(default='x', max_length=60),
        ),
        migrations.AddField(
            model_name='fachbereich',
            name='urlbezeichnung',
            field=models.SlugField(default='x', max_length=60),
        ),
        migrations.AddField(
            model_name='konkretewettbewerbsrunde',
            name='urlbezeichnung',
            field=models.SlugField(default='x', max_length=60),
        ),
        migrations.AddField(
            model_name='person',
            name='urlbezeichnung',
            field=models.SlugField(default='x', max_length=60),
        ),
        migrations.AddField(
            model_name='seminar',
            name='urlbezeichnung',
            field=models.SlugField(default='x', max_length=60),
        ),
        migrations.AddField(
            model_name='teilnahmekonzept',
            name='urlbezeichnung',
            field=models.SlugField(default='x', max_length=60),
        ),
        migrations.AddField(
            model_name='veranstaltung',
            name='urlbezeichnung',
            field=models.SlugField(default='x', max_length=60),
        ),
        migrations.AddField(
            model_name='wettbewerb',
            name='urlbezeichnung',
            field=models.SlugField(default='x', max_length=60),
        ),
        migrations.AddField(
            model_name='wettbewerbsrunde',
            name='urlbezeichnung',
            field=models.SlugField(default='x', max_length=60),
        ),
    ]
