# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Margarete', '0006_auto_20160818_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeminarTeilnahme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Margarete.Person')),
                ('teilnahmeart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Margarete.ArtTeilnahme')),
                ('veranstaltung', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Margarete.KonkretesSeminar')),
            ],
        ),
        migrations.CreateModel(
            name='SonstigeTeilnahme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Margarete.Person')),
                ('teilnahmeart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Margarete.ArtTeilnahme')),
                ('veranstaltung', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Margarete.SonstigeVeranstaltung')),
            ],
        ),
        migrations.CreateModel(
            name='WettbewerbsTeilnahme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Margarete.Person')),
                ('teilnahmeart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Margarete.ArtTeilnahme')),
                ('veranstaltung', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Margarete.Wettbewerbsveranstaltung')),
            ],
        ),
        migrations.RemoveField(
            model_name='teilnahme',
            name='person',
        ),
        migrations.RemoveField(
            model_name='teilnahme',
            name='teilnahmeart',
        ),
        migrations.RemoveField(
            model_name='teilnahme',
            name='veranstaltung',
        ),
        migrations.RemoveField(
            model_name='veranstaltung',
            name='teilnehmer',
        ),
        migrations.DeleteModel(
            name='Teilnahme',
        ),
        migrations.AddField(
            model_name='konkretesseminar',
            name='teilnehmer',
            field=models.ManyToManyField(through='Margarete.SeminarTeilnahme', to='Margarete.Person'),
        ),
        migrations.AddField(
            model_name='sonstigeveranstaltung',
            name='teilnehmer',
            field=models.ManyToManyField(through='Margarete.SonstigeTeilnahme', to='Margarete.Person'),
        ),
        migrations.AddField(
            model_name='wettbewerbsveranstaltung',
            name='teilnehmer',
            field=models.ManyToManyField(through='Margarete.WettbewerbsTeilnahme', to='Margarete.Person'),
        ),
    ]
