# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 10:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Margarete', '0009_auto_20160914_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sonstigeteilnahme',
            name='veranstaltung',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Margarete.SonstigeVeranstaltung'),
        ),
    ]
