# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 10:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Margarete', '0010_auto_20160914_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teilnahme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='seminarteilnahme',
            name='person',
        ),
        migrations.RemoveField(
            model_name='seminarteilnahme',
            name='teilnahmeart',
        ),
        migrations.RemoveField(
            model_name='seminarteilnahme',
            name='veranstaltung',
        ),
        migrations.RemoveField(
            model_name='sonstigeteilnahme',
            name='person',
        ),
        migrations.RemoveField(
            model_name='sonstigeteilnahme',
            name='teilnahmeart',
        ),
        migrations.RemoveField(
            model_name='sonstigeteilnahme',
            name='veranstaltung',
        ),
        migrations.RemoveField(
            model_name='wettbewerbsteilnahme',
            name='person',
        ),
        migrations.RemoveField(
            model_name='wettbewerbsteilnahme',
            name='teilnahmeart',
        ),
        migrations.RemoveField(
            model_name='wettbewerbsteilnahme',
            name='veranstaltung',
        ),
        migrations.RemoveField(
            model_name='artteilnahme',
            name='urlbezeichnung',
        ),
        migrations.RemoveField(
            model_name='fachbereich',
            name='urlbezeichnung',
        ),
        migrations.RemoveField(
            model_name='konkretesseminar',
            name='teilnehmer',
        ),
        migrations.RemoveField(
            model_name='konkretewettbewerbsrunde',
            name='urlbezeichnung',
        ),
        migrations.RemoveField(
            model_name='person',
            name='urlbezeichnung',
        ),
        migrations.RemoveField(
            model_name='seminar',
            name='urlbezeichnung',
        ),
        migrations.RemoveField(
            model_name='sonstigeveranstaltung',
            name='teilnehmer',
        ),
        migrations.RemoveField(
            model_name='teilnahmekonzept',
            name='urlbezeichnung',
        ),
        migrations.RemoveField(
            model_name='veranstaltung',
            name='urlbezeichnung',
        ),
        migrations.RemoveField(
            model_name='wettbewerb',
            name='urlbezeichnung',
        ),
        migrations.RemoveField(
            model_name='wettbewerbsrunde',
            name='urlbezeichnung',
        ),
        migrations.RemoveField(
            model_name='wettbewerbsveranstaltung',
            name='teilnehmer',
        ),
        migrations.DeleteModel(
            name='SeminarTeilnahme',
        ),
        migrations.DeleteModel(
            name='SonstigeTeilnahme',
        ),
        migrations.DeleteModel(
            name='WettbewerbsTeilnahme',
        ),
        migrations.AddField(
            model_name='teilnahme',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Margarete.Person'),
        ),
        migrations.AddField(
            model_name='teilnahme',
            name='teilnahmeart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Margarete.ArtTeilnahme'),
        ),
        migrations.AddField(
            model_name='teilnahme',
            name='veranstaltung',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Margarete.Veranstaltung'),
        ),
        migrations.AddField(
            model_name='veranstaltung',
            name='teilnehmer',
            field=models.ManyToManyField(through='Margarete.Teilnahme', to='Margarete.Person'),
        ),
    ]
