# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Margarete', '0011_auto_20160914_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='artteilnahme',
            name='urlbezeichnung',
            field=models.SlugField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fachbereich',
            name='urlbezeichnung',
            field=models.SlugField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='konkretewettbewerbsrunde',
            name='urlbezeichnung',
            field=models.SlugField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='urlbezeichnung',
            field=models.SlugField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='seminar',
            name='urlbezeichnung',
            field=models.SlugField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teilnahmekonzept',
            name='urlbezeichnung',
            field=models.SlugField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='veranstaltung',
            name='urlbezeichnung',
            field=models.SlugField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='wettbewerb',
            name='urlbezeichnung',
            field=models.SlugField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='wettbewerbsrunde',
            name='urlbezeichnung',
            field=models.SlugField(blank=True, max_length=20, null=True),
        ),
    ]
