# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-09 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Margarete', '0012_auto_20160914_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='artteilnahme',
            name='wert',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
