# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-10 11:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Margarete', '0013_artteilnahme_wert'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='teilnahmearten',
            field=models.ManyToManyField(to='Margarete.Teilnahmekonzept'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='fachbereich',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Margarete.Fachbereich'),
        ),
    ]
