# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-10 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Margarete', '0014_auto_20161010_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='konkretesseminar',
            name='jahr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='konkretesseminar',
            name='nummer',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='konkretewettbewerbsrunde',
            name='nummer',
            field=models.IntegerField(default=1),
        ),
    ]
