# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-10 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Margarete', '0015_auto_20161010_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='sonstigeveranstaltung',
            name='teilnahmearten',
            field=models.ManyToManyField(to='Margarete.Teilnahmekonzept'),
        ),
    ]
