# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-12 10:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Margarete', '0017_seminar_gehoertzuwettbewerbsrunde'),
    ]

    operations = [
        migrations.AddField(
            model_name='sonstigeveranstaltung',
            name='istNachtreffenVon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nachtreffen', to='Margarete.Veranstaltung'),
        ),
    ]
